### ISSUE TITLE
How about hcs201

### ISSUE THREAD

**Issue by mrnsms** [leech001/HCS301#1]
Any way for coding hcs201?

**Comment by leech001** [comment]
Not in this library explicitly. But the encoding is very similar. You can change the code yourself for HCS201 based on this library.
![image](https://user-images.githubusercontent.com/17683444/210318208-9951533d-b7f5-40e0-8af0-6a69aba38b8f.png)

Or you can try to write the parameters in the library https://github.com/leech001/RF-BARRIER there is a little easier to do.

The description of the new code should be done in https://github.com/leech001/RF-BARRIER/blob/master/Src/rf-barrier-timings.h

**Comment by mrnsms** [comment]
i wish i could do that... ive just started studying this.
anyway to help me out? i just really want to make it works for my gate

**Comment by leech001** [comment]
Hi.
I have compared in detail the datasheets for HCS201 and HCS301, there is no difference in signal coding. So the library should fit the HCS201 without any changes
![image](https://user-images.githubusercontent.com/17683444/210948620-5221905b-9eb7-4038-b585-b36da932a8e3.png)

![image](https://user-images.githubusercontent.com/17683444/210949001-99425f45-971c-4200-8492-788a1e31124d.png)

So try it all should work.
